holocene: operator fee
alloy-rs/op-alloy pull request #130
Opened 2024-09-30 18:48 UTC by yuwen01

Adds the operator fee, as described in https://github.com/ethereum-optimism/design-docs/pull/81 and [this spec](https://github.com/ethereum-optimism/specs/pull/382/files)

2024-09-30 19:57 UTC, mattsse approved these changes
this looks correct to me,

pending @refcell sanity check

2024-09-30 20:06 UTC, refcell requested changes
Isthmus is a different hardfork than Holocene. We'll need to add an entirely new `L1BlockInfo` type for Isthmus.

This should be done by:
- Leaving holocene types unchanged.
- Introducing a new variant in the [`L1BlockInfo` enum](https://github.com/alloy-rs/op-alloy/blob/main/crates/protocol/src/block_info.rs#L47) called `Isthmus` that wraps a new `L1BlockInfoIsthmus` struct.
- Add a `is_isthmus_active` method to the `RollupConfig` with `isthmus_time` field.
- Add the operator fee parsing inside `try_new` when creating a new `L1BlockInfoTx` behind a `if rollup_config.is_isthmus_active(l2_block_time)` branch **above** the holocene check since it _follows_ the holocene hardfork.

2024-09-30 20:08 UTC, yuwen01 commented
Sorry for the miscommunication -- since this feature is almost ready, I have verbal confirmation from tynes that it's very likely to be included in the Holocene hardfork. I'll update the spec shortly.

2024-09-30 21:12 UTC, refcell commented
> Sorry for the miscommunication -- since this feature is almost ready, I have verbal confirmation from tynes that it's very likely to be included in the Holocene hardfork. I'll update the spec shortly.

I don't believe tynes is correct here. The Holocene feature set has been frozen for a little while now with implementation well on the way. It's most likely these changes will need to be a part of Isthmus. We have channels in [our discord](https://discord.gg/mHR9gRKAfT) to discuss hardfork changes. I'd recommend joining the discord and kicking off a thread in `#hf-next` channel about adding these changes and linking your spec pr.

2024-10-01 01:54 UTC, tynes commented
We have general consensus on these changes being included in a future hardfork when they are ready. We should all make sure we agree on the design before saying anything is ready for inclusion

2024-11-21 21:42 UTC, refcell commented
Hey @yuwen01, since there were a ton of merge conflicts due to changes I've introduced over the past month or so, I've went ahead and updated this based off [your spec pr in ethereum-optimism/specs](https://github.com/ethereum-optimism/specs/pull/382). Feel free to push changes if the spec changes or callout anything that doesn't look right to you :D

2024-11-21 21:43 UTC, refcell approved these changes

2024-11-21 21:44 UTC, refcell commented
> [!WARNING]
>
> This is blocked from merging until [the spec](https://github.com/ethereum-optimism/specs/pull/382) has been merged.

2024-12-04 00:02 UTC, refcell commented
cc @emhane if you haven't seen this pr yet

2024-12-11 20:15 UTC, emhane approved these changes
lgtm

2024-12-11 20:15 UTC, emhane commented on crates/protocol/src/info/variant.rs
> +        };
```suggestion
        let L1BlockInfoTx::Isthmus(decoded) =
            L1BlockInfoTx::decode_calldata(RAW_ISTHMUS_INFO_TX.as_ref()).expect("Wrong fork");
```

2025-01-04 00:50 UTC, refcell commented on crates/protocol/src/info/variant.rs
> +        };
This turns out not to work because the other variants of the `L1BlockInfoTx` are not covered

2025-01-05 15:54 UTC, emhane commented on crates/protocol/src/info/variant.rs
> +        };
could be a nice issue to open to rust-lang :)

2025-01-08 18:43 UTC, refcell commented
Replaced by https://github.com/op-rs/maili/pull/10

2025-01-08 18:43 UTC, closed without merging

2025-02-06 09:45 UTC, leruaa commented
@refcell  as per @mattsse comment: https://github.com/paradigmxyz/reth/pull/14243#issuecomment-2639267098

Can this PR be merged?