feat(consensus): op-alloy-consensus
alloy-rs/op-alloy pull request #8
Opened 2024-05-20 18:13 UTC by refcell

**Description**

Maintains commit history with #4 and updates trait types.

2024-05-21 08:57 UTC, mattsse requested changes
only one q re receipt variants

2024-05-21 08:57 UTC, mattsse commented on crates/op-consensus/src/transaction/optimism.rs
this should be moved to deposit.rs

2024-05-21 08:57 UTC, mattsse commented on crates/op-consensus/src/receipt/envelope.rs
> +    Legacy(OpReceiptWithBloom<T>),
hmm, this doesn't feel right to use the Opdepositreceipt for all variants

can we replicate the eth variants and only modify the deposit variant?

2024-06-12 14:11 UTC, refcell commented on crates/op-consensus/src/transaction/envelope.rs
> +            127 => OpTxType::Deposit,
ibid `126`, can we also just match on `DEPOSIT_TX_TYPE_ID`?

2024-06-12 14:11 UTC, refcell commented on crates/op-consensus/src/transaction/envelope.rs
> +            127 => Self::Deposit,
```suggestion
            126 => Self::Deposit,
```

2024-06-12 14:36 UTC, mattsse approved these changes

2024-06-12 14:36 UTC, merged