Feat(op-alloy-protocol): add deposit module
alloy-rs/op-alloy pull request #81
Opened 2024-09-08 05:10 UTC by DoTheBestToGetTheBest

related https://github.com/anton-rs/kona/issues/509

2024-09-08 15:11 UTC, refcell requested changes
Request to remove `anyhow` as a dependency.

2024-09-08 15:11 UTC, refcell commented on Cargo.toml
> +anyhow = { version = "1.0.86", default-features = false }
Let's avoid using `anyhow`

2024-09-08 15:11 UTC, refcell commented on crates/protocol/Cargo.toml
> +anyhow.workspace = true
Remove anyhow

2024-09-08 15:11 UTC, refcell commented on crates/protocol/src/deposits.rs
> +    Custom(anyhow::Error),
I think we should use a generic here that implements the [`core::error::Error`](https://doc.rust-lang.org/core/error/trait.Error.html) trait.

e.g.
```rust
pub enum DepositError<T: impl core::error::Error> {
	...
	/// A custom [core::error::Error].
	Custom(T)
}
```

2024-09-08 20:09 UTC, DoTheBestToGetTheBest commented
ty for the fast review; made all changes you requested

2024-09-09 12:44 UTC, refcell approved these changes

2024-09-09 12:44 UTC, merged

2024-09-09 14:15 UTC, mattsse commented
this did not pass CI