replace u8 direction field with Direction type
alloy-rs/op-alloy pull request #90
Opened 2024-09-11 17:52 UTC by DoTheBestToGetTheBest

according to https://github.com/ethereum-optimism/optimism/blob/40750a58e7a4a6f06370d18dfe6c6eab309012d9/op-node/p2p/rpc_api.go#L26C24-L26C38

implementation reference https://github.com/libp2p/go-libp2p/blob/d55bed5f78fad923353b92c7d1db64c758bcbf9c/core/network/network.go#L26

2024-09-12 06:02 UTC, mattsse requested changes

2024-09-12 06:02 UTC, mattsse commented on crates/rpc-types/src/net.rs
> +    DirOutbound = 2,
lets drop the Dir prefix

2024-09-12 06:02 UTC, mattsse commented on crates/rpc-types/src/net.rs
> +#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
does this serde as number?

please add a test

2024-09-12 06:02 UTC, mattsse commented on crates/rpc-types/src/net.rs
> +}
don't think we can do this, mapping unsupported numbers to inbound doesn't feel right, please convert to tryfrom

2024-09-12 15:11 UTC, DoTheBestToGetTheBest commented
done  @mattsse thanks

2024-09-22 13:47 UTC, mattsse approved these changes

2024-09-22 13:53 UTC, merged